home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views, user_login
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.home, name="home"),
    path('contact', views.contact, name="contact"),
    path('about', views.about, name="about"),
    path('404', views.PAGE_NOT_FOUND, name= "404"),
    path('search', views.SEARCH_COURSE, name='search_course'),

    # course detail pages
    path('courses', views.single_course, name="single_course"),
    path('courses/filter-data',views.filter_data,name="filter-data"),
    path('course/<slug:slug>', views.COURSE_DETAILS, name="course_details"),
    path('course/watch-course/<slug:slug>', views.WATCH_COURSE, name="watch_course"),

    # Registration and Login detail
    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/register', user_login.REGISTER, name= "register"),
    # path('dologin', user_login.DO_LOGIN, name= "dologin"),
    # path('accounts/profile', user_login.PROFILE, name= "profile"),
    # path('accounts/profile/update', user_login.PROFILE_UPDATE, name= "profile_update"),

    # payment and confirmation
    # path('checkout/<slug:slug>', views.CHECKOUT, name="checkout"),
    # path('verify_payment', views.VERIFY_PAYMENT, name="verify_payment"),



    # path('test-series', views.TEST_SERIES, name="test_series"),
    # path('my_profile', views.MY_PROFILE, name="my_profile"),
    # path('Questions/<int:qno>', views.exam_home, name='exam_home'),

    # user course detail
    path('my-course', views.MY_COURSE, name="my_course"),
    path('my-course/<slug:slug>', views.MY_COURSE_SLUG, name='my_course_slug'),
    path('my-test-series', views.MY_TEST_SERIES, name="my_test_series"),
    path('my-test-series/<slug:slug>', views.MY_TEST_SERIES_SLUG, name="my_test_series_slug"),


    # Question page
    path('instructions/<slug>', views.instructions, name="instructions"),
    path('Question/<slug>', views.Question, name="Question"),
    path('submit/<slug>', views.SUBMIT, name="submit"),


    # view explanation
    path('result_explanation/<slug>', views.result_d, name="result_d"),
    # path('Questions/<slug>', views.QUESTIONS, name="questions"),

    # Video Detail
    path('my-videos', views.MY_VIDEOS, name="my_videos"),
    path('my-videos/<slug:slug>', views.MY_VIDEOS_SLUG, name="my_videos_slug"),
    path('my-videos/video_lecture/<slug>', views.video_lecture, name="video_lecture"),

    # E-Book detail
    path('my-e-books', views.MY_E_BOOKS, name="my_e-books"),
    path('my-e-books/<slug:slug>', views.MY_E_BOOKS_SLUG, name="my_e-books"),
    path('my-e-books/e-book/<slug>', views.E_BOOK, name="e-book"),


    # path('result/<slug>', views.RESULT, name="result"),
    # path('score_card/<slug>', views.SCORE_CARD, name="score_card"),

    # AJAX detail
    path('number/', views.number_que, name="number"),
    path('next/', views.next_que, name="next"),
    path('mark/', views.mark_que, name="mark"),
    path('que_page/', views.que_page, name="que_page"),
    # path('exp_page/', views.exp_page, name="exp_page"),
    path('next_exp/', views.next_exp, name="next_exp"),
    path('number_exp/', views.number_exp, name="number_exp"),
    
    # path('test_page/', views.test_page, name="test_page"),

    
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

macn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('payment/', include('payment.urls')),
    path('', include('home.urls')),
    
    
    
    
    
]

home/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.conf import settings
from autoslug import AutoSlugField

# Create your models here.
class Categories(models.Model):
    
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='home/images', default="")

    def __str__(self):
        return self.name

    def get_all_category(self):
        return Categories.objects.all().order_by('id')

class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    name = models.CharField(max_length=100, null=True)
    field = models.CharField(max_length=100, null=True)
    about_author = models.TextField()

    def __str__(self):
        return self.name

class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language

class Course(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="Media/featured_img",null=True)
    featured_video = models.CharField(max_length=300,null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    level = models.ForeignKey(Level,on_delete=models.CASCADE,null=True)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    DeadLine = models.CharField(max_length=500, null=True)
    language = models.ForeignKey(Language,on_delete=models.CASCADE,null=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    validity = models.CharField(max_length=100,null=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("course_details", kwargs={'slug': self.slug})

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Course)


class Course_Features(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=300)

    def __str__(self):
        return self.points

class Requirements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=300)

    def __str__(self):
        return self.points


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " = " + self.course.title


class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/Yt_Thumbnail", null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    youtube_id = models.CharField(max_length=300)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
class Subject(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to="Media/subject", null=True)
    subject_name = models.CharField(max_length=200)
    title = models.CharField(max_length=300, null=True)
    total_que = models.CharField(max_length=300, null=True)
    total_marks = models.CharField(max_length=300, null=True)
    slug_s = AutoSlugField(populate_from='title', unique=True, null=True, default=None)
    

    def __str__(self):
        return self.subject_name + " = " + self.course.title
    
    
class Video_Lecture(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/lecture", null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=300)
    video = models.FileField(upload_to="Media/video", null=True)

    def __str__(self):
        return self.title
    
class E_Book(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/lecture", null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=300)
    book = models.FileField(upload_to="Media/book", null=True)

    def __str__(self):
        return self.title


class Ppr(models.Model):
    serial_number = models.IntegerField(null=True)
    title = models.CharField(max_length=300, null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE, null=True)
    new_slug = AutoSlugField(populate_from='title', unique=True, null=True, default=None)
    
    time_duration = models.IntegerField(null=True)
    

    def __str__(self):
        return self.title

class Que(models.Model):
    id = models.AutoField(primary_key=True)
    qs_no=models.IntegerField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE,null=True)
    ppr = models.ForeignKey(Ppr, on_delete=models.CASCADE,null=True)
    subject = models.CharField(max_length=300, null=True)
    questions=models.TextField(null=True)
    image = models.ImageField(upload_to='Media/que', blank=True, null=True)
    answers=models.CharField(max_length=20, null=True)
    option_a=models.TextField(null=True)
    image_a = models.ImageField(upload_to='Media/ans', blank=True, null=True)
    option_b=models.TextField(null=True)
    image_b = models.ImageField(upload_to='Media/ans', blank=True, null=True)
    option_c=models.TextField(null=True)
    image_c = models.ImageField(upload_to='Media/ans', blank=True, null=True)
    option_d=models.TextField(null=True)
    image_d = models.ImageField(upload_to='media/ans', blank=True, null=True)
    disc=models.TextField(null=True)
    def __str__(self):
        return 'Q.'+ str(self.qs_no)  + ')  '+  self.questions


class Ans(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE, null= True)
    ppr=models.ForeignKey(Ppr,on_delete=models.CASCADE, null=True)
    que_no=models.IntegerField(default=1)
    que=models.ForeignKey(Que,on_delete=models.CASCADE)
    answer=models.CharField(max_length=20, null=True)
    correct_answer=models.CharField(max_length=20, null=True)
    mark = models.IntegerField(default=0)
    score=models.FloatField(default=0)
    # date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.answer

class Result(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE, null=True)
    ppr=models.ForeignKey(Ppr,on_delete=models.CASCADE, null=True)
    correct_answer=models.IntegerField(default=0)
    wrong_answer=models.IntegerField(default=0)
    not_answer=models.IntegerField(default=0)
    
    def __str__(self):
        return self.student.username
    
class Time(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE, null= True)
    ppr = models.ForeignKey(Ppr,on_delete=models.CASCADE, null=True)
    time = models.IntegerField(default=0)
    def __str__(self):
        return self.student.username

        
class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=1)
    expiry_date = models.DateTimeField(null=True, blank=True)
    

    def __str__(self):
        return self.user.first_name + " " + self.course.title




# class Payment(models.Model):
#     order_id = models.CharField(max_length=100,null=True, blank=True)
#     payment_id = models.CharField(max_length=100,null=True, blank=True)
#     signature_id = models.CharField(max_length=100,null=True, blank=True)
#     user_course = models.ForeignKey(UserCourse, on_delete=models.CASCADE, null=True)
#     user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
#     date = models.DateTimeField(auto_now_add=True)
#     status = models.BooleanField(default=False)

#     def __str__(self):
#         return self.user.first_name + " " + self.course.title


class Contact(models.Model):
    name = models.CharField(max_length=50,null=True, blank=True)
    email = models.CharField(max_length=70, null=True, blank=True)
    desc = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.email


class Test(models.Model):
    test=models.CharField(max_length=150,unique=True)
    
    def __str__(self):
        return self.test

templates/profile/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Register page</title>
        <link rel="shortcut icon" href="img/favicon.ico">
        <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Roboto:500,400italic,100,700italic,300,700,500italic,400" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <style>
            /* Chrome, Safari and Opera syntax */
            :-webkit-full-screen { 
               background-color: #f2f7f8; 
             }
            
            /* Firefox syntax */
            :-moz-full-screen {
              background-color: #f2f7f8;
            }
            
            /* IE/Edge syntax */
            :-ms-fullscreen {
              background-color:#f2f7f8;
            }
            
            /* Standard syntax */
            :fullscreen {
              background-color:#f2f7f8;
            }
            
            </style>
        
        <body>
        <div id="container" class="cls-container" >
            {% block 'body'%}
            {% endblock %}
        </div>
        <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
        <!--BootstrapJS [ RECOMMENDED ]-->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        
            
            </script>
            
     </body>

</html>

templates/profile/my_test_series.html
{% extends 'base.html' %}
{% load static %}
{% load course_tags %}

{% block title %} {{course.title}} My Test Series {% endblock title %}

{% block content %}

<style>
    .dormant{
        pointer-events: none;
  cursor: default;
    }
    #time{
        color:blue;
    }
</style>

 <!-- PAGE TITLE
    ================================================== -->

      
    



    <header class="py-8 py-md-09" style="background-image: none;">
        <div class="container text-center py-xl-2">
            <h1 class="display-4 fw-semi-bold mb-0">My Test Series</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                    <li class="breadcrumb-item">
                        <a class="text-gray-800" href="{% url 'home' %}">
                            Home
                        </a>
                    </li>
                    <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                        My Test Series
                    </li>
                </ol>
            </nav>
        </div>
        <!-- Img -->
        <img class="d-none img-fluid" src="...html" alt="...">
    </header>


    <!-- CONTROL BAR
    ================================================== -->
    

    <!-- COURSE LIST V1
    ================================================== -->
    <div class="container pb-4 pb-xl-7">
        {% include 'components/msg.html' %}
        <div class="row row-cols-md-2 row-cols-xl-3 mb-6 mb-xl-3">
            {% for i in course %}
            {% if i.status == 1 %}
                        <div class="col-12 col-md-6 col-xl-4 col-wd-3 pb-4 pb-md-7" style="padding-right:15px;padding-left:15px;">
                            <!-- Card -->
                            <div class="card border shadow p-2 rounded-lg sk-fade">
                                
    
                                <div class="card-zoom position-relative">
                                    <div class="badge-float sk-fade-top top-0 right-0 mt-4 me-4">
                                       

                                        
                                    </div>

                                    <a href="my-test-series/{{i.course.slug}}" class="card-img sk-thumbnail img-ratio-9 d-block">
                                        <img class="rounded shadow-light-lg" src="/{{i.course.featured_image}}" alt="...">
                                    </a>

                                    
                                </div>

                                <!-- Footer -->
                                <div class="card-footer px-2 pb-2 mb-1 pt-4 position-relative">
                                    <a href="my-test-series/{{i.course.slug}}" class="d-block">
                                        <div class="avatar avatar-xl badge-float position-absolute top-0 right-0 mt-n6 me-5 rounded-circle shadow border border-white border-w-lg">
                                            <img src="{{i.course.author.author_profile}}" alt="..." class="avatar-img rounded-circle">
                                        </div>
                                    </a>

                                    <!-- Preheading -->
                                    <a href="my-test-series/{{i.course.slug}}"><span class="mb-1 d-inline-block text-gray-800">{{i.course.category.name}}</span></a>


                                    <!-- Heading -->
                                    <div class="position-relative">
                                        <a href="my-test-series/{{i.course.slug}}" class="d-block stretched-link"><h4 class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">{{i.course.title}}</h4></a>

                                        

                                        <span id="time"> Expires on {{i.expiry_date.date}}</span>
                                                            
                                                           
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="col-12 col-md-6 col-xl-4 col-wd-3 pb-4 pb-md-7 dormant" style="padding-right:15px;padding-left:15px;">
                            <!-- Card -->
                            <div class="card border shadow p-2 rounded-lg sk-fade">
                                
    
                                <div class="card-zoom position-relative">
                                    <div class="badge-float sk-fade-top top-0 right-0 mt-4 me-4">
                                       

                                        
                                    </div>

                                    <a href="my-test-series/{{i.course.slug}}" class="card-img sk-thumbnail img-ratio-9 d-block">
                                        <img class="rounded shadow-light-lg" src="/{{i.course.featured_image}}" alt="...">
                                    </a>

                                    
                                </div>

                                <!-- Footer -->
                                <div class="card-footer px-2 pb-2 mb-1 pt-4 position-relative">
                                    <a href="my-test-series/{{i.course.slug}}" class="d-block">
                                        <div class="avatar avatar-xl badge-float position-absolute top-0 right-0 mt-n6 me-5 rounded-circle shadow border border-white border-w-lg">
                                            <img src="{{i.course.author.author_profile}}" alt="..." class="avatar-img rounded-circle">
                                        </div>
                                    </a>

                                    <!-- Preheading -->
                                    <a href="my-test-series/{{i.course.slug}}"><span class="mb-1 d-inline-block text-gray-800">{{i.course.category.name}}</span></a>


                                    <!-- Heading -->
                                    <div class="position-relative">
                                        <a href="my-test-series/{{i.course.slug}}" class="d-block stretched-link"><h4 class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">{{i.course.title}}</h4></a>

                                        

                                        Expired on <span>{{i.expiry_date.date}}</span>
                                                           
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                         {% endfor %}
            </div>
            
        </div>

        

        
    </div>

{% endblock %}

templates/profile/online_test.html
{% extends 'base.html' %}
{% load static %}
{% load course_tags %}

{% block title %} {{course.title}} My Test Series {% endblock title %}

{% block content %}

<!-- <script>
    
    distance = 60 * 60 * 1000;
    sessionStorage.setItem('distance', distance)
</script> -->


<!-- PAGE TITLE
    ================================================== -->

<header class="py-8 py-md-9" style="background-image: none;">
    <div class="container text-center py-xl-2">
        <h1 id="course" class="display-4 fw-semi-bold mb-0">{{course.title}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                <li class="breadcrumb-item">
                    <a class="text-gray-800" href="">
                        Online Test Series
                    </a>
                </li>

            </ol>
        </nav>
    </div>
    <!-- Img -->
    <img class="d-none img-fluid" src="...html" alt="...">
</header>

<!-- COURSE LIST V1
    ================================================== -->
<div class="container pb-4 pb-xl-7">
    {% include 'components/msg.html' %}
    <div class="row row-cols-md-2 row-cols-xl-3 mb-6 mb-xl-3">
        {% for i in course.ppr_set.all %}
        <div class="col-12 col-md-6 col-xl-4 col-wd-3 pb-4 pb-md-7" style="padding-right:15px;padding-left:15px;">
            <!-- Card -->
            <div class="card border shadow p-2 rounded-lg sk-fade">
                <div class="card-zoom position-relative">
                    <a href="" class="card-img sk-thumbnail img-ratio-9 d-block">
                        <img class="rounded shadow-light-lg" src="/{{i.course.featured_image}}" alt="...">
                    </a>
                </div>



                <!-- Footer -->
                <div class="card-footer px-2 pb-2 mb-1 pt-4 position-relative">


                    <!-- Preheading -->

                    <!-- Heading -->
                    <div class="position-relative">
                        <a class="d-block stretched-link">
                            <h4 id="ppr" class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">{{ i.title }} </h4>
                        </a>

                    </div>

                    <div style="display:flex; justify-content: space-between;">

                        <a href=""
                            style="border:4px solid rgba(var(--bs-gigas-rgb)); padding:4px; border-radius: 8px; color:white; background-color: rgba(var(--bs-gigas-rgb)); "
                            onclick="window.open('/instructions/{{i.new_slug}}', toolbar=0, statusbar=0, locationbar=0)">
                            Start Test
                        </a>

                        <a href=""
                            style="border:4px solid rgba(var(--bs-gigas-rgb)); padding:4px; border-radius: 8px;  color:white; background-color: rgba(var(--bs-gigas-rgb)); "
                            onclick="window.open('/result_explanation/{{i.new_slug}}', toolbar=0, statusbar=0, locationbar=0)">
                            View Result
                        </a>
                    </div>


                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

<br>


<script>

    console.log(w)

    function onClick() {
        newWindow = window.open("/result_explanation/{{i.new_slug}}", toolbar = 0, statusbar = 0, locationbar = 0);
    }
</script>
{% endblock %}